on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use wasmtime 5.0.0
      uses: mwilliamson/setup-wasmtime-action@v2
      with:
        wasmtime-version: "5.0.0"
    - name: Build unit tests
      uses: swiftwasm/swiftwasm-action@v5.7
      with:
        shell-action: swift build -c debug --product pod-runtime-class-policyPackageTests -Xswiftc -color-diagnostics --triple wasm32-unknown-wasi
    - name: Run unit tests
      run: |
        wasmtime run --trap-unknown-imports .build/wasm32-unknown-wasi/debug/pod-runtime-class-policyPackageTests.wasm

  e2e_tests:
    name: end to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v1
      - name: install wasm-strip
        run: |
          export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
          sudo apt-get -q update
          sudo apt-get -q install -y wabt binaryen

      - name: Build policy
        uses: swiftwasm/swiftwasm-action@v5.7
        with:
          shell-action: swift build -c release --triple wasm32-unknown-wasi

      -
        name: optimize policy
        run: |
          # need to fix file permissions because of some issue with Swift Foundation and filesystem
          sudo chmod 777 .build/wasm32-unknown-wasi/release/Policy.wasm
          wasm-strip .build/wasm32-unknown-wasi/release/Policy.wasm
          wasm-opt -Os .build/wasm32-unknown-wasi/release/Policy.wasm -o policy.wasm

      - name: Run e2e tests
        run: |
          make e2e-tests
